from src.constants.my_enum import MyEnumJS, unique


@unique
class EnumCommand(MyEnumJS):
    ASSERT = "assert"
    ASSERT_TITLE = "assertTitle"
    ASSERT_TEXT = "assertText"
    ASSERT_NOT_TEXT = "assertNotText"
    ASSERT_VALUE = "assertValue"
    ASSERT_CHECKED = "assertChecked"
    ASSERT_NOT_CHECKED = "assertNotChecked"
    ASSERT_ELEMENT_PRESENT = "assertElementPresent"
    ASSERT_ELEMENT_NOT_PRESENT = "assertElementNotPresent"
    ASSERT_EDITABLE = "assertEditable"
    ASSERT_NOT_EDITABLE = "assertNotEditable"
    ASSERT_SELECTED_LABEL = "assertSelectedLabel"
    ASSERT_SELECTED_VALUE = "assertSelectedValue"
    ASSERT_NOT_SELECTED_VALUE = "assertNotSelectedValue"
    ASSERT_ALERT = "assertAlert"
    ASSERT_CONFIRMATION = "assertConfirmation"
    ASSERT_PROMPT = "assertPrompt"
    # CmdBrowser
    OPEN = "open"
    CLOSE = "close"
    SET_WINDOW_SIZE = "setWindowSize"
    STORE_WINDOW_HANDLE = "storeWindowHandle"
    SELECT_WINDOW = "selectWindow"
    # CmdConditional
    IF = "if"
    ELSE_IF = "elseIf"
    ELSE = "else"
    END = "end"
    # CmdInput
    TYPE = "type"
    SEND_KEYS = "sendKeys"
    SUBMIT = "submit"
    EDIT_CONTENT = "editContent"
    # CmdLoop
    WHILE = "while"
    TIMES = "times"
    FOR_EACH = "forEach"
    DO = "do"
    REPEAT_IF = "repeatIf"
    # end_ = "end"
    # CmdMouse
    CLICK = "click"
    CLICK_AT = "clickAt"
    DOUBLE_CLICK = "doubleClick"
    DOUBLE_CLICK_AT = "doubleClickAt"
    MOUSE_DOWN = "mouseDown"
    MOUSE_DOWN_AT = "mouseDownAt"
    MOUSE_MOVE_AT = "mouseMoveAt"
    MOUSE_UP = "mouseUp"
    MOUSE_UP_AT = "mouseUpAt"
    DRAG_AND_DROP_TO_OBJECT = "dragAndDropToObject"
    MOUSE_OVER = "mouseOver"
    MOUSE_OUT = "mouseOut"
    # CmdPopupWindow
    ANSWER_ON_NEXT_PROMPT = "answerOnNextPrompt"
    CHOOSE_CANCEL_ON_NEXT_PROMPT = "chooseCancelOnNextPrompt"
    CHOOSE_OK_ON_NEXT_CONFIRMATION = "chooseOkOnNextConfirmation"
    CHOOSE_CANCEL_ON_NEXT_CONFIRMATION = "chooseCancelOnNextConfirmation"
    WEBDRIVER_ANSWER_ON_VISIBLE_PROMPT = "webdriverAnswerOnVisiblePrompt"
    WEBDRIVER_CHOOSE_CANCEL_ON_VISIBLE_PROMPT = "webdriverChooseCancelOnVisiblePrompt"
    WEBDRIVER_CHOOSE_OK_ON_VISIBLE_CONFIRMATION = "webdriverChooseOkOnVisibleConfirmation"
    WEBDRIVER_CHOOSE_CANCEL_ON_VISIBLE_CONFIRMATION = "webdriverChooseCancelOnVisibleConfirmation"
    # CmdScript
    RUN_SCRIPT = "runScript"
    EXECUTE_SCRIPT = "executeScript"
    EXECUTE_ASYNC_SCRIPT = "executeAsyncScript"
    # CmdSelection
    SELECT = "select"
    ADD_SELECTION = "addSelection"
    REMOVE_SELECTION = "removeSelection"
    SELECT_FRAME = "selectFrame"
    CHECK = "check"
    UNCHECK = "uncheck"
    # CmdStore
    STORE = "store"
    STORE_TITLE = "storeTitle"
    STORE_JSON = "storeJson"
    STORE_TEXT = "storeText"
    STORE_VALUE = "storeValue"
    STORE_ATTRIBUTE = "storeAttribute"
    STORE_XPATH_COUNT = "storeXpathCount"
    # storeWindowHandle_ = "storeWindowHandle"
    # CmdTestTools
    ECHO = "echo"
    PAUSE = "pause"
    SET_SPEED = "setSpeed"
    DEBUGGER = "debugger"
    RUN = "run"
    # CmdVerify
    VERIFY = "verify"
    VERIFY_TITLE = "verifyTitle"
    VERIFY_TEXT = "verifyText"
    VERIFY_NOT_TEXT = "verifyNotText"
    VERIFY_VALUE = "verifyValue"
    VERIFY_CHECKED = "verifyChecked"
    VERIFY_NOT_CHECKED = "verifyNotChecked"
    VERIFY_ELEMENT_PRESENT = "verifyElementPresent"
    VERIFY_ELEMENT_NOT_PRESENT = "verifyElementNotPresent"
    VERIFY_EDITABLE = "verifyEditable"
    VERIFY_NOT_EDITABLE = "verifyNotEditable"
    VERIFY_SELECTED_LABEL = "verifySelectedLabel"
    VERIFY_SELECTED_VALUE = "verifySelectedValue"
    VERIFY_NOT_SELECTED_VALUE = "verifyNotSelectedValue"
    # CmdWait
    WAIT_FOR_TEXT = "waitForText"
    WAIT_FOR_ELEMENT_PRESENT = "waitForElementPresent"
    WAIT_FOR_ELEMENT_NOT_PRESENT = "waitForElementNotPresent"
    WAIT_FOR_ELEMENT_VISIBLE = "waitForElementVisible"
    WAIT_FOR_ELEMENT_NOT_VISIBLE = "waitForElementNotVisible"
    WAIT_FOR_ELEMENT_EDITABLE = "waitForElementEditable"
    WAIT_FOR_ELEMENT_NOT_EDITABLE = "waitForElementNotEditable"
    CONDITIONALS = [IF, ELSE_IF, ELSE, WHILE, TIMES, FOR_EACH]
    NEXT_COMMAND_TO_PASS = [ELSE_IF, ELSE, END]
    TO_AFTER_COMMAND = [ELSE_IF, ELSE]
